name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore ./CompositeState/CompositeState.sln
    - name: Build
      run: dotnet build ./CompositeState/CompositeState.sln --no-restore 
    - name: Test
      run: |
        dotnet test ./CompositeState/CompositeState.sln --collect:"XPlat Code Coverage" --logger trx --results-directory coverage --no-build --verbosity normal
        cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
    - name: Create Coverage Artifact
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.4
      with:
        reports: 'coverage/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline'
        verbosity: 'Info'
        toolpath: 'reportgeneratortool'
    - name: Publish Coverage Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport 
        path: coveragereport 
    - name: Create Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage Summary to PullRequest
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
