name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./CompositeState/CompositeState.sln
    - name: Build
      run: dotnet build ./CompositeState/CompositeState.sln --no-restore 
    - name: Test
      run: dotnet test ./CompositeState/CompositeState.sln --no-build --verbosity normal
